name: ARM64 Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Build ARM64 Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t my-app:arm64 .

      - name: Run tests
        run: |
          docker run --platform linux/arm64 my-app:arm64 pytest