name: DXVK

permissions:
  contents: write

on:
  schedule:
    - cron:  '0 0 1,17 * *'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Build DXVK
        run: |
          gh run download $(gh run list --repo doitsujin/dxvk --json databaseId,workflowName --jq '.[] | select(.workflowName == "Artifacts (Package)") | .databaseId' | head -n 1) --repo doitsujin/dxvk
          cd dxvk*
          mv x32 syswow64
          mv x64 system32
          cd -
          mv dxvk* windows
          zip -r DXVK-dev.zip windows
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: DXVK
          files: |
            ./DXVK-dev.zip
          