name: Turnip Main

on:
  schedule:
    - cron:  '0 0 1,17 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
      - name: Build Turnip
        run: |
          sudo sed -i "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/ubuntu.sources
          sudo cat /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep mesa
          sudo apt install clang libclang-dev libllvmspirvlib-17-dev libudev-dev libclc-19-dev cargo build-essential git meson ninja-build python3-mako python3-pip libdrm-dev libwayland-dev wayland-protocols glslang-tools
          git clone https://gitlab.freedesktop.org/Pipetto-crypto/mesa.git --recurse-submodules
          cd mesa
          pip install meson
          cargo install bindgen-cli
          meson build-freedreno -D platforms=x11 -Dgallium-drivers= -D vulkan-drivers=freedreno -D libunwind=disabled -D microsoft-clc=disabled -D valgrind=disabled -D freedreno-kmds=kgsl,msm
          ninja -C build-freedreno
          find . -iname "libvulkan_freedreno.so"