name: Turnip Main

permissions:
  contents: write

on:
  schedule:
    - cron:  '20 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
      - name: Build Turnip
        run: |
          sudo sed -i "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/ubuntu.sources
          sudo cat /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep mesa
          git clone https://gitlab.freedesktop.org/Pipetto-crypto/mesa.git -b winlator_wsi-termux-x11 --depth=1
          cd mesa
          meson build-freedreno -D platforms=x11 -Dgallium-drivers= -D vulkan-drivers=freedreno -D libunwind=disabled -D microsoft-clc=disabled -D valgrind=enabled -D freedreno-kmds=kgsl,msm
          ninja -C build-freedreno
          cd build-freedreno/src/freedreno/vulkan/
          7z a Turnip-dev.7z libvulkan_freedreno.so
      - uses: actions/upload-artifact@v4
        with:
          name: Turnip WSI
          path: ./mesa/build-freedreno/src/freedreno/vulkan/libvulkan_freedreno.so
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Turnip
          files: |
            ./mesa/build-freedreno/src/freedreno/vulkan/Turnip-dev.7z