name: Turnip Main

on:
  schedule:
    - cron:  '0 0 1,17 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Turnip
        run: |
          sudo echo "deb-src http://archive.ubuntu.com/ubuntu/ noble main restricted
" >> /etc/apt/sources.list
          sudo cat /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep mesa
          sudo apt install llvm-spirv libudev-dev libclc-19-dev cargo build-essential git meson ninja-build python3-mako python3-pip libdrm-dev libwayland-dev wayland-protocols glslang-tools
          git clone https://gitlab.freedesktop.org/Pipetto-crypto/mesa.git --recurse-submodules
          cd mesa
          pip install meson
          cargo install bindgen-cli
          meson setup build
          ninja -C build/
          find . -iname "libvulkan_freedreno.so"