name: Turnip Wrapper

permissions:
  contents: write

on:
  schedule:
    - cron:  '0 0 1,17 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
      - name: Build Turnip Wrapper
        run: |
          sudo sed -i "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/ubuntu.sources
          sudo cat /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep mesa
          git clone https://gitlab.freedesktop.org/Pipetto-crypto/mesa.git -b winlator_wsi-termux-x11 --depth=1
          cd mesa
          meson build-freedreno -D platforms=x11 -Dgallium-drivers= -D vulkan-drivers=virtio -D libunwind=disabled -D microsoft-clc=disabled -D valgrind=disabled -D freedreno-kmds=virtio
          ninja -C build-freedreno
      - uses: actions/upload-artifact@v4
        with:
          name: Turnip Wrapper
          path: ./mesa/build-freedreno/
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Wrapper
          files: |
            ./mesa/build-freedreno/src/virtio/vulkan/libvulkan_virtio.so